services:
  seifenrechner:
    image: ghcr.io/immer-gut/seifenrechner:latest
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: any
