services:
  seifenrechner:
    image: seifenrechner:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: any

